version: '3'

tasks:
  default:
    desc: Pull and build prx
    cmds:
      - git pull
      - task: build

  build:
    desc: Build prx binary
    sources:
      - ./*.go
      - go.mod
      - go.sum
    generates:
      - /home/dnk/bin/prx
    cmds:
      - go build -o ~/bin/prx .

  clean:
    desc: Remove prx binary
    cmds:
      - rm -f ~/bin/prx
